# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick Young
tagline:          'Internal Product Manager @ Facebook'
description:      'I like to write software and kiteboard'
url:              http://nickyoung.io
baseurl:          /

author:
  name:           'Nick Young'
  url:            https://fb.me/n1ck

paginate:         5
